#!/usr/bin/env perl

use strict;
use warnings;
use AnyEvent::Strict;
use AnyEvent::Socket;
use AnyEvent::Handle::UDP;
 
use IO::Socket::INET;
use XML::Simple ':strict';
use Data::Dumper;
 
my ($socket,$data);
my $datagram;
my $datagram_count=0;

my $udp_ready = AnyEvent->condvar;
 
my $hfauto_rx = AnyEvent::Handle::UDP->new(
    bind => ['10.34.34.34', 15080],
    on_recv => sub {
        my ($datagram, $ae_handle, $sock_addr) = @_;
        my ($service, $host) = AnyEvent::Socket::unpack_sockaddr($sock_addr);
        $datagram_count++;
        print "packet number $datagram_count, ", length($datagram),
              " bytes from ", format_address($host),"\n",
              $datagram;
        print "\n\n";

        my $hfauto = XMLin($datagram, KeyAttr => 'HFAUTO', ForceArray => 0);
        print Dumper $hfauto;
    });

$udp_ready->recv;
